"""add_delivery_location

Revision ID: 14a3a0a9058a
Revises: 38f318e8c9e4
Create Date: 2026-09-20 11:43:47.628448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14a3a0a9058a'
down_revision: Union[str, None] = '38f318e8c9e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rfqs', sa.Column('delivery_location', sa.String(length=255), server_default='N/A', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rfqs', 'delivery_location')
    # ### end Alembic commands ###
