"""cascade user delete

Revision ID: 38f318e8c9e4
Revises: 34db51b80262
Create Date: 2026-09-20 10:57:18.373735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38f318e8c9e4'
down_revision: Union[str, None] = '34db51b80262'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('quotes_vendor_id_fkey', 'quotes', type_='foreignkey')
    op.create_foreign_key(None, 'quotes', 'users', ['vendor_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('rfqs_buyer_id_fkey', 'rfqs', type_='foreignkey')
    op.create_foreign_key(None, 'rfqs', 'users', ['buyer_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rfqs', type_='foreignkey')
    op.create_foreign_key('rfqs_buyer_id_fkey', 'rfqs', 'users', ['buyer_id'], ['id'], ondelete='RESTRICT')
    op.drop_constraint(None, 'quotes', type_='foreignkey')
    op.create_foreign_key('quotes_vendor_id_fkey', 'quotes', 'users', ['vendor_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###
